### ISSUE TITLE
Request: Also publish to open-vsx.org

### ISSUE THREAD

**Issue by aidalgol** [KTXSoftware/vscode-krom#12]
Could this please also be published to the [open-vsx.org](https://open-vsx.org/) extension gallery?  This would make it easier to install in [VSCodium](https://vscodium.com/) (the free/libre build of VSCode).  Instructions on how to do this are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by RobDangerous** [comment]
See Kode/vscode-kha-extension-pack#4
