### ISSUE TITLE
Krom debugger doesn't start

### ISSUE THREAD

**Issue by MoritzBrueckner** [KTXSoftware/vscode-krom#13]
When trying to run a Kha project in Krom from VSCode, no (visible) process will open after the build is done. There is no window flickering, nothing. The debug panel where you can pause the process or step through the code closes again and there are no visible error messages. This happens even with the empty `Kha: Init Project` template.

The Kha path setting in VSCode is set to `[...]\Forks\Kha`, the Krom path setting to `[...]\Forks\Krom_bin` and both repositories are unmodified (including submodules) and are checked out at the current master. I'm using the latest VSCodium version on Windows 10 and the latest version of the Krom extension (installed as .vsix because it is VSCodium).

There are no errors in the VSCodium developer console (`Ctrl + Shift + I`).

Build output:
```
> Executing task: node [...]\Forks\Kha\make.js krom --debug <

Using Kha (8f4ec9b2) from [...]\Forks\Kha
Creating Kha project.
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.

Terminal will be reused by tasks, press any key to close it.
```

Installed VSCode extensions (that I deem relevant):
- Debugger for Krom: v20.6.0
- Haxe: v2.32.2
- Kha: v21.9.0
- Kha Extension Pack: v21.3.0
- krafix: v18.7.1
- Krom: v20.1.0

As far as I can tell all these extensions use the latest available version.

This problem already exists for a long time (at least half a year, if not even for more than one year) and some other users on the Armory Discord experience the same issues.

**Comment by RobDangerous** [comment]
Fixed.
