### ISSUE TITLE
Krom Binaries are Outdated

### ISSUE THREAD

**Issue by lunabunn** [KTXSoftware/vscode-krom#3]
Right now, when trying to debug with Krom in VSC using this extension, Krom fails to run saying `Krom uses API version 1 but Kha targets API version 2. Please update Krom.`.

https://github.com/Kode/Krom_bin/commit/786b20c06ef552117b8a0c0aba4c50911fc5bed7 should work for Linux and Windows, but AFAIK won't work for OSX. Problem is, the newest commit to that repo breaks compatibility again on Windows, this time by being too new... So I guess no OSX support D:

Anyway, the submodule in this repo should be updated to the commit I linked above; if VSC Krom not being up-to-date is somehow a conscious decision, `Init Kha` command should not create a Krom launch task.

Sorry I can't create a PR because I don't have experience with Git submodules T-T

**Comment by RobDangerous** [comment]
Things always get out of sync because I do too many things. But you can manually use the latest version of everything by setting the khaPath and kromPath options in vscode. Set khaPath to a checkout of Kha and kromPath to a checkout of Krom_bin.

**Comment by lunabunn** [comment]
IK Krom path can be specified, and I have set that up with a newer copy of Krom_bin. Just seems counterintuitive (and quite beginner-unfriendly) to me that Init Kha sets up a Krom launch task by default, yet the Krom binaries shipped with the Kha Extension Pack hasn't been updated in a year (and thus, does not work). But alas, I guess it's a minor inconvenience.

Just a thought, but maybe Krom binaries shouldn't be included in this extension at all? If we need to use  our own copy of Krom anyway, (and I understand it is inconvenient to update Krom binaries time after time) I think it would make more sense to not ship Krom binaries with the extension at all, then make it clear we have to get our own copy of Krom for Krom debug to work.

**Comment by RobDangerous** [comment]
Nah, the whole process can potentially be automated but currently I just do not have the time to work on smaller inconveniences.
